######################################################################
## RESEARCH PROJECT: "Blood count parameters as early biomarkers for therapeutic outcome in cutaneous leishmaniasis: a retrospective cohort in Colombia"
## PRINCIPAL INVESTIGATOR & SCRIPT DEVELOPER: DAVID ESTEBAN REBELLON SANCHEZ
## PROJECT SUPERVISORS: MARIA ADELAIDA GOMEZ & LYDA OSORIO
## FINAL MANUSCRIPT CO-AUTHORS WHO APPROVED THE ANALYSIS: David E. Rebellón-Sánchez, Lina Giraldo-Parra, Jimena Jojoa, Jonny A. García-Luna, Lyda Osorio, María Adelaida Gómez
## SPONSORING INSTITUTION: CENTRO INTERNACIONAL DE ENTRENAMIENTO E INVESTIGACIONES MEDICAS (CIDEIM) AND UNIVERSIDAD DEL VALLE
######################################################################

#### SCRIPT FOR DATA CLEANING AND EXPLORATORY ANALYSIS OF THE DATABASES
# INPUT: FINAL EXPORTS OF THE DATABASES AFTER DATA COLLECTION USING CASE REPORT FORMS
# PROCESS: MERGE, CLEAN, AND EXPLORE THE DATA
# OUTPUT: EXPLORATORY ANALYSIS REPORT stored in "Reports" and FINAL CLEAN DATABASES stored in "data/Clean_data" 

# Package installation (if not already installed)
# install.packages("readxl")    ## Read Excel files
# install.packages("PASWR")     ## Contains an EDA function that facilitates exploratory analysis
# install.packages("DataExplorer") ## Multiple functions for exploratory analysis and report building
# install.packages("skimr")     ## Useful for calculating averages for a selected group
# install.packages("dplyr")     ## For data manipulation in analyses
# install.packages("foreign")     ## For reading/writing .dta files
# install.packages("ggthemes")  ## For customizing graphs in reports
# install.packages("ggplot2")   ## For custom plots
# install.packages("gtsummary") ## For creating summary tables

## Clear workspace ##
rm(list = ls())

## Load libraries
library(readxl)      ## Read Excel files
library(PASWR)       ## EDA functions for exploratory analysis
library(DataExplorer)## Multiple functions for exploratory analysis and report building
library(skimr)       ## For calculating group summaries
library(dplyr)
library(ggthemes)    ## For customizing graphs in reports
library(ggplot2)     ## For custom plots
library(foreign)     ## For reading/writing .dta files
library(gtsummary)   ## For creating summary tables


###
### DATA INPUT
###

# The databases stored on CIDEIM's servers were imported. These databases were generated by trained medical personnel after 
# reviewing all clinical records and adhering to the research protocols and study definitions. 
# The data was entered through double data entry, and any inconsistencies were verified and re-entered. 
# The data was input into a form created and supported by SQL. Participants were anonymized and assigned a study participant code randomly 
# using a locally designated application for this purpose.
# 
# Given that the case report form was structured by modules corresponding to each study visit or component (e.g., inclusion criteria verification, 
# enrollment visit, follow-up visit, laboratory variables, microorganism variables, final status, etc.), there is a dataset for each aspect of the study.
# 
# In the datasets, '8' represents missing data ('no data') and '9' represents 'not applicable' (i.e., the information is not relevant for that case or visit).

participantes <- read_excel("data/participantes.xlsx", 
                            na = c("8","88","888","8888","9","99","999","9999"))

criterios_inclusion <- read_excel("data/criterios.xlsx", 
                                  na = c("8","88","888","8888","9","99","999","9999"))

evaluacion_base <- read_excel("data/eval_bas.xlsx", 
                              na = c("8","88","888","8888","9","99","999","9999"))

fin_tto <- read_excel("data/fin_tto.xlsx",
                      na = c("8","88","888","8888","9","99","999","9999"))

hemopre <- read_excel("data/hemo_pre.xlsx",
                      na= c("8888","999","9999"))

hemopos <- read_excel("data/hemo_pos.xlsx",
                      na= c("8888","999","9999"))

sem_8 <- read_excel("data/sem_8.xlsx",
                    na = c("8","88","888","8888","9","99","999","9999")) 

sem_13 <- read_excel("data/sem_13.xlsx",
                     na = c("8","88","888","8888","9","99","999","9999")) 

sem_26 <- read_excel("data/sem_26.xlsx",
                     na = c("8","88","888","8888","9","99","999","9999"))

visita_adic <- read_excel("data/visita_adic.xlsx",
                          na = c("8","88","888","8888","9","99","999","9999"))

especie_parasit <- read_excel("data/espes_para.xlsx",
                              na = c("8","88","888","8888","9","99","999","9999"))

estado_fin <- read_excel("data/estado_fin.xlsx",
                         na = c("8","88","888","8888","9","99","999","9999"))


##################
## SECTION A. DATA VISUALIZATION, VARIABLE TYPE RECODING, DATA CLEANING,
## AND ASSIGNMENT OF LABELS FOR EACH DATABASE
##################

#### PARTICIPANTS DATABASE
str(criterios_inclusion)
head(criterios_inclusion)
# No adjustments required


EDA(hemopre$recuen_neutro_pre_tto)

####
#### Inclusion Criteria Database
####

str(criterios_inclusion)
head(criterios_inclusion)
criterios_inclusion$fecha_evaluacion_ci <- as.Date(criterios_inclusion$fecha_evaluacion_ci, format = "%YY-%MM-%DD")
criterios_inclusion$fecha_evaluacion_ci[criterios_inclusion$fecha_evaluacion_ci <= "2000-01-01"] <- NA
criterios_inclusion$criterio_inc_1_ci <- factor(criterios_inclusion$criterio_inc_1_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_inc_2_ci <- factor(criterios_inclusion$criterio_inc_2_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_inc_3_ci <- factor(criterios_inclusion$criterio_inc_3_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_inc_4_ci <- factor(criterios_inclusion$criterio_inc_4_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_inc_5_ci <- factor(criterios_inclusion$criterio_inc_5_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_inc_6_ci <- factor(criterios_inclusion$criterio_inc_6_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_exc_1_ci <- factor(criterios_inclusion$criterio_exc_1_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$criterio_exc_2_ci <- factor(criterios_inclusion$criterio_exc_2_ci,
                                                levels = c("0", "1"),
                                                labels= c("No", "Yes"))
criterios_inclusion$paciente_enrolado_ci <- factor(criterios_inclusion$paciente_enrolado_ci,
                                                   levels = c("0", "1"),
                                                   labels= c("No", "Yes"))
criterios_inclusion$fechaHoraCreacion <- as.Date(criterios_inclusion$fechaHoraCreacion, format = "%YY-%MM-%DD")
criterios_inclusion$fechaHoraCreacion[criterios_inclusion$fechaHoraCreacion <= "2000-01-01"] <- NA

####
#### Baseline Evaluation Database
####

str(evaluacion_base)
head(evaluacion_base)
evaluacion_base$fecha_evaluacion_eb <- as.Date(evaluacion_base$fecha_evaluacion_eb, format = "%YY-%MM-%DD")
evaluacion_base$fecha_evaluacion_eb[evaluacion_base$fecha_evaluacion_eb <= "2000-01-01"] <- NA
evaluacion_base$visita_eval_realizada_eb <- factor(evaluacion_base$visita_eval_realizada_eb,
                                                   levels = c("0", "1"),
                                                   labels= c("No", "Yes"))
evaluacion_base$fecha_visita_eb <- as.Date(evaluacion_base$fecha_visita_eb, format= "%YY-%MM-%DD")
evaluacion_base$fecha_visita_eb[evaluacion_base$fecha_visita_eb <= "2000-01-01"] <- NA

EDA(evaluacion_base$edad_eb)
evaluacion_base <- evaluacion_base %>% 
  mutate (edad_categorica = case_when(
    evaluacion_base$edad_eb >= 17 & evaluacion_base$edad_eb < 45   ~ "0",
    evaluacion_base$edad_eb >= 1 & evaluacion_base$edad_eb < 7  ~ "1",
    evaluacion_base$edad_eb >= 7 & evaluacion_base$edad_eb < 17   ~ "2",
    evaluacion_base$edad_eb >= 45 & evaluacion_base$edad_eb < 60   ~ "5",
    evaluacion_base$edad_eb >= 60 ~ "6"))
### Reference categories obtained from: https://journals.scholarpublishing.org/index.php/ASSRJ/article/view/2924/1717

evaluacion_base$edad_categorica <- factor(evaluacion_base$edad_categorica,
                                          levels = c("0", "1", "2", "5", "6"),
                                          labels= c("Between 17 and 44", "Between 1 and 6", 
                                                    "Between 7 and 16", "Between 45 and 59", 
                                                    "60 or older"))

evaluacion_base$sexo_nacimiento_eb
evaluacion_base$sexo_nacimiento_eb[evaluacion_base$sexo_nacimiento_eb == 2] <- 0
evaluacion_base$sexo_nacimiento_eb <- factor(evaluacion_base$sexo_nacimiento_eb,
                                             levels = c("0", "1"),
                                             labels= c("Female", "Male"))

evaluacion_base$grupo_etnico_eb[evaluacion_base$grupo_etnico_eb == 3] <- 0
evaluacion_base$grupo_etnico_eb <- factor(evaluacion_base$grupo_etnico_eb,
                                          levels = c("0", "1", "2"),
                                          labels= c("Mestizo", "Afro-Colombian", "Indigenous"))

evaluacion_base$infeccion_concom_eb <- factor(evaluacion_base$infeccion_concom_eb,
                                              levels = c("0", "1"),
                                              labels = c("No","Yes"))

evaluacion_base$comorbilidades_eb <- factor(evaluacion_base$comorbilidades_eb,
                                            levels = c("0", "1"),
                                            labels = c("No","Yes"))

EDA(evaluacion_base$num_comorbilidades_eb)
names (evaluacion_base)[11] = "comorb_cardio"
names (evaluacion_base)[12] = "comorb_respira"
names (evaluacion_base)[13] = "comorb_gastroint"
names (evaluacion_base)[14] = "comorb_endocrin"
names (evaluacion_base)[15] = "comorb_neuro"
names (evaluacion_base)[16] = "comorb_otra"
evaluacion_base$comorb_cardio <- factor(evaluacion_base$comorb_cardio,
                                        levels = c("0", "1"),
                                        labels = c("No","Yes"))
evaluacion_base$comorb_respira <- factor(evaluacion_base$comorb_respira,
                                         levels = c("0", "1"),
                                         labels = c("No","Yes"))
evaluacion_base$comorb_gastroint <- factor(evaluacion_base$comorb_gastroint,
                                           levels = c("0", "1"),
                                           labels = c("No","Yes"))
evaluacion_base$comorb_endocrin <- factor(evaluacion_base$comorb_endocrin,
                                          levels = c("0", "1"),
                                          labels = c("No","Yes"))
evaluacion_base$comorb_neuro <- factor(evaluacion_base$comorb_neuro,
                                       levels = c("0", "1"),
                                       labels = c("No","Yes"))
evaluacion_base$comorb_otra <- factor(evaluacion_base$comorb_otra,
                                      levels = c("0", "1"),
                                      labels = c("No","Yes"))
evaluacion_base$historia_previa_eb <- factor(evaluacion_base$historia_previa_eb,
                                             levels = c("0", "1"),
                                             labels = c("No","Yes"))

EDA(evaluacion_base$tiempo_sin_actual_eb)

evaluacion_base %>% 
  filter(tiempo_sin_actual_eb > 26) %>% 
  dplyr::select(codigo_paciente)

## Patients with a symptom duration over 26 weeks were identified;
## Some patients have symptoms for up to 24 months; these outliers are valid

EDA(evaluacion_base$peso_eb)
evaluacion_base %>% 
  group_by(edad_categorica) %>% 
  skim(peso_eb)
## Distribution appears non-normal, likely due to age

EDA(evaluacion_base$talla_eb)
evaluacion_base %>% 
  group_by(edad_categorica) %>% 
  skim(talla_eb)
## Distribution appears non-normal, with some outliers

## Convert height (cm) to meters for BMI calculation
evaluacion_base$talla_mt_eb <- (evaluacion_base$talla_eb / 100)
evaluacion_base$imc <- (evaluacion_base$peso_eb / (evaluacion_base$talla_mt_eb * evaluacion_base$talla_mt_eb))

EDA(evaluacion_base$imc)
evaluacion_base %>%
  filter(imc > 35) %>%
  dplyr::select(codigo_paciente, imc, talla_eb, talla_mt_eb, peso_eb, edad_eb)

## The miscoded heights for patients PH1057 and PH3031 have been corrected in the database

## Create categorical BMI variable
evaluacion_base <- evaluacion_base %>% 
  mutate (imc_categorico = case_when(
    imc >= 18 & imc <= 25   ~ "0",
    imc < 18  ~ "1",
    imc > 25 & imc <= 30   ~ "2",
    imc > 30 & imc <= 35   ~ "3",
    imc > 35 ~ "4"))

evaluacion_base$imc_categorico <- factor(evaluacion_base$imc_categorico,
                                         levels = c("0", "1", "2", "3", "4"),
                                         labels = c("Between 18 and 25 (Normal)",
                                                    "Less than 18",
                                                    "Greater than 25 up to 30",
                                                    "Greater than 30 up to 35",
                                                    "Greater than 35"))

evaluacion_base  <- evaluacion_base  %>% 
  mutate(imc_cat_corta = case_when(
    evaluacion_base$imc >= 18 & evaluacion_base$imc <= 25 ~ "0",
    evaluacion_base$imc < 18 ~ "1",
    evaluacion_base$imc > 25 ~ "2"))

evaluacion_base$imc_cat_corta  <- factor(evaluacion_base$imc_cat_corta, 
                                         levels = c("0", "1", "2"), 
                                         labels = c("Between 18 and 25 (Normal)",
                                                    "Less than 18 (Underweight)",
                                                    "Greater than 25 (Overweight and Obesity)"))

## Verify number of lesions
EDA(evaluacion_base$num_lesiones_pre_eb)

## Create categories for lesions
evaluacion_base <- evaluacion_base %>% 
  mutate (lesiones_categorica = case_when(
    num_lesiones_pre_eb == 1 ~ "0",
    num_lesiones_pre_eb == 2 ~ "1", 
    num_lesiones_pre_eb >= 3 ~ "2"))

evaluacion_base$lesiones_categorica <- factor(evaluacion_base$lesiones_categorica,
                                              levels = c("0", "1", "2"),
                                              labels= c("One lesion", "Two lesions", 
                                                        "Three or more lesions"))

## Lesion type
evaluacion_base$tipo_lesion_eb <- factor(evaluacion_base$tipo_lesion_eb,
                                         levels = c("1", "2", "3", "4", "6"),
                                         labels = c("Ulcer", "Nodule", "Papule",
                                                    "Plaque", "Other"))
## Regional lymphadenopathy
evaluacion_base$linfa_regional_eb <- factor(evaluacion_base$linfa_regional_eb,
                                            levels = c("0", "1"),
                                            labels = c("No", "Yes"))

## Prescribed treatment
evaluacion_base$tto_prescrito_eb <- factor(evaluacion_base$tto_prescrito_eb,
                                           levels = c("1", "2", "3"),
                                           labels = c("Glucantime", "Miltefosine", "Glucantime + Pentoxifylline"))
## Glucantime dosage
EDA(evaluacion_base$poso_glu_pres_eb)
## Miltefosine dosage
EDA(evaluacion_base$poso_mil_pres_eb)
summary(evaluacion_base$poso_mil_pres_eb)

## Calculate Glucantime dose per weight
evaluacion_base$dosis_glu_pres <- ((evaluacion_base$poso_glu_pres_eb * 81) / evaluacion_base$peso_eb)
summary(evaluacion_base$dosis_glu_pres)

## Calculate Miltefosine dose per weight
evaluacion_base$dosis_mil_pres <- (evaluacion_base$poso_mil_pres_eb / evaluacion_base$peso_eb)
summary(evaluacion_base$dosis_mil_pres)

## Abnormal Glucantime dose
evaluacion_base <- evaluacion_base %>% 
  mutate (dosis_glu_anormal = case_when(
    dosis_glu_pres >= 10 & dosis_glu_pres <= 20  ~ "0",
    dosis_glu_pres > 20 ~ "1",
    dosis_glu_pres < 10 ~ "2"))

evaluacion_base$dosis_glu_anormal <- factor(evaluacion_base$dosis_glu_anormal,
                                            levels = c("0", "1", "2"),
                                            labels = c("Normal range", "Above therapeutic range", "Below therapeutic range"))
table(evaluacion_base$dosis_glu_anormal)

## Abnormal Miltefosine dose
evaluacion_base <- evaluacion_base %>% 
  mutate (dosis_mil_anormal = case_when(
    dosis_mil_pres >= 1.5 & dosis_mil_pres <= 2.5  ~ "0",
    dosis_mil_pres > 2.5 ~ "1",
    dosis_mil_pres < 1.5 ~ "2"))
evaluacion_base$dosis_mil_anormal <- factor(evaluacion_base$dosis_mil_anormal,
                                            levels = c("0", "1", "2"),
                                            labels = c("Normal range", "Above therapeutic range", "Below therapeutic range"))
table(evaluacion_base$dosis_mil_anormal)

## Unified dose range (combined)
evaluacion_base <- evaluacion_base %>% 
  mutate (rango_dosis_medicamento = case_when(
    dosis_glu_anormal == "Normal range" | dosis_mil_anormal == "Normal range" ~ "0",
    dosis_glu_anormal == "Above therapeutic range" | dosis_mil_anormal == "Above therapeutic range" ~ "1",
    dosis_glu_anormal == "Below therapeutic range" | dosis_mil_anormal == "Below therapeutic range" ~ "2"))

evaluacion_base$rango_dosis_medicamento <- factor(evaluacion_base$rango_dosis_medicamento,
                                                  levels = c("0", "1", "2"),
                                                  labels = c("Normal range", "Overdose", "Underdose"))
table(evaluacion_base$rango_dosis_medicamento)

## Check treatment days ordered
EDA(evaluacion_base$dias_tto_ordenado_eb)

## Check total ampoules and capsules ordered
table(evaluacion_base$total_amp_glu_eb)
table(evaluacion_base$total_amp_mil_50_eb)
table(evaluacion_base$total_amp_cap_10_eb)

## Generate dose summary to verify consistency among treatment, dosage, and quantity ordered
evaluacion_base %>% 
  dplyr::select(tto_prescrito_eb, poso_glu_pres_eb, poso_mil_pres_eb, total_amp_glu_eb,
                total_amp_mil_50_eb, total_amp_cap_10_eb) %>% 
  gtsummary::tbl_summary(by= tto_prescrito_eb, 
                         missing_text = "Not applicable / missing",
                         label = list(poso_glu_pres_eb = "Glucantime prescribed (ml)", 
                                      poso_mil_pres_eb = "Miltefosine prescribed (mg)",
                                      total_amp_glu_eb = "Total Glucantime ampoules ordered for treatment",
                                      total_amp_mil_50_eb = "Total 50 mg Miltefosine capsules ordered", 
                                      total_amp_cap_10_eb = "Total 10 mg Miltefosine capsules ordered"),
                         type = c("total_amp_glu_eb","total_amp_cap_10_eb", "total_amp_mil_50_eb") ~ "continuous")

## Creation date
evaluacion_base$fechaHoraCreacion <- as.Date(evaluacion_base$fechaHoraCreacion, format = "%YY-%MM-%DD")
evaluacion_base$fechaHoraCreacion[evaluacion_base$fechaHoraCreacion <= "2000-01-01"] <- NA

####
#### End of Treatment Database
####

str(fin_tto)
head(fin_tto)
fin_tto$fecha_evaluacion_ftto <- as.Date(fin_tto$fecha_evaluacion_ftto, format = "%YY-%MM-%DD")
fin_tto$fecha_evaluacion_ftto[fin_tto$fecha_evaluacion_ftto <= "2000-01-01"] <- NA
fin_tto$visita_eval_realizada_ftto <- factor(fin_tto$visita_eval_realizada_ftto,
                                             levels = c("0", "1"),
                                             labels= c("No", "Yes"))

fin_tto$fecha_visita_ftto <- as.Date(fin_tto$fecha_visita_ftto, format = "%YY-%MM-%DD")
fin_tto$fecha_visita_ftto[fin_tto$fecha_visita_ftto <= "2000-01-01"] <- NA
fin_tto$dias_transcurridos_ftto <- as.numeric((difftime(fin_tto$fecha_visita_ftto, evaluacion_base$fecha_visita_eb,
                                                        units = "weeks"))*7)
summary(fin_tto$dias_transcurridos_ftto)

fin_tto %>%
  filter(dias_transcurridos_ftto <15) %>%
  dplyr::select(codigo_paciente)

fin_tto$infeccion_concom_ftto <- factor(fin_tto$infeccion_concom_ftto,
                                        levels = c("0", "1"),
                                        labels= c("No", "Yes"))

EDA(fin_tto$num_les_pos_tto_ftto)

## Lesion type for end of treatment
fin_tto$tipo_lesion_ftto <- factor(fin_tto$tipo_lesion_ftto,
                                   levels = c("1", "2", "3", "4", "5", "6","7"),
                                   labels = c("Ulcer","Nodule", "Papule",
                                              "Plaque", "Scar with active border",
                                              "Other", "Scar"))
# NOTE: Lesion changes have occurred

## Create variable in end of treatment identical to the pre-treatment lesion
fin_tto$tipo_lesion_eb <- evaluacion_base$tipo_lesion_eb

## Create a variable summarizing lesion change
fin_tto <- fin_tto %>% 
  mutate (cambio_lesion = case_when(
    tipo_lesion_eb == "Ulcera" & tipo_lesion_ftto == "Ulcera" ~ "0",
    tipo_lesion_eb == "Ulcera" & tipo_lesion_ftto == "Placa" ~ "1",
    tipo_lesion_eb == "Ulcera" & tipo_lesion_ftto == "Papula" ~ "2",
    tipo_lesion_eb == "Ulcera" & tipo_lesion_ftto == "Cicatriz con borde activo" ~ "3",
    tipo_lesion_eb == "Ulcera" & tipo_lesion_ftto == "Otra" ~ "4",
    tipo_lesion_eb == "Placa" & tipo_lesion_ftto == "Placa" ~ "5",
    tipo_lesion_eb == "Placa" & tipo_lesion_ftto == "Ulcera" ~ "6",
    tipo_lesion_eb == "Placa" & tipo_lesion_ftto == "Cicatriz con borde activo" ~ "7",
    tipo_lesion_eb == "Papula" & tipo_lesion_ftto == "Ulcera" ~ "8",
    tipo_lesion_eb == "Nodulo" & tipo_lesion_ftto == "Placa" ~ "9",
    tipo_lesion_eb == "Otra" & tipo_lesion_ftto == "Ulcera" ~ "10",
    tipo_lesion_eb == "Otra" & tipo_lesion_ftto == "Otra" ~ "11"
  ))

fin_tto$cambio_lesion <- factor(fin_tto$cambio_lesion,
                                levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"),
                                labels= c("Ulcer - Ulcer", 
                                          "Ulcer - Plaque", 
                                          "Ulcer - Papule",
                                          "Ulcer - Scar with active border",
                                          "Ulcer - Other", 
                                          "Plaque - Plaque",
                                          "Plaque - Ulcer", 
                                          "Plaque - Scar with active border",
                                          "Papule - Ulcer",
                                          "Nodule - Plaque", 
                                          "Other - Ulcer", 
                                          "Other - Other"))

## Verify the changes
table(fin_tto$cambio_lesion)


fin_tto <- fin_tto %>% 
  mutate (cambio_lesion2 = case_when(
    cambio_lesion == "Ulcer - Ulcer" ~ "1",
    cambio_lesion == "Ulcer - Plaque" ~ "0",
    cambio_lesion %in% c("Ulcer - Papule", "Ulcer - Other", "Plaque - Plaque", "Plaque - Ulcer", 
                         "Plaque - Scar with active border", "Papule - Ulcer", 
                         "Nodule - Plaque", "Other - Ulcer", "Other - Other") ~ "2"
  ))

fin_tto$cambio_lesion2 <- factor(fin_tto$cambio_lesion2,
                                 levels = c("0", "1", "2"),
                                 labels = c("Ulcer - Plaque", "Ulcer - Ulcer", "Other changes"))

## Regional lymphadenopathy
fin_tto$linfa_regional_ftto <- factor(fin_tto$linfa_regional_ftto,
                                      levels = c("0", "1"),
                                      labels= c("No", "Yes"))

EDA(fin_tto$dias_tto_admido_ftto)

## Verify no patient has less than 18 or more than 28 treatment days
fin_tto %>%
  filter(dias_tto_admido_ftto < 18) %>%
  dplyr::select(codigo_paciente)

fin_tto %>%
  filter(dias_tto_admido_ftto >28) %>%
  dplyr::select(codigo_paciente)

## Create adherence variable (percentage of administered days / ordered days)
fin_tto$porcent_adheren_dias = (fin_tto$dias_tto_admido_ftto / evaluacion_base$dias_tto_ordenado_eb)*100

table(fin_tto$porcent_adheren_dias)

## Create adherence variable based on ampoules ordered (Glucantime)
fin_tto$porcent_adheren_ampoll_glc = (fin_tto$total_amp_glu_ftto / evaluacion_base$total_amp_glu_eb)*100
table(fin_tto$porcent_adheren_ampoll_glc)

# Quality control: flag patients with adherence below 90%
fin_tto %>%
  filter(porcent_adheren_ampoll_glc <90) %>%
  dplyr::select(codigo_paciente, porcent_adheren_ampoll_glc, total_amp_glu_ftto, dias_tto_admido_ftto)

## Adherence for Miltefosine 50 mg capsules
fin_tto$porcent_adheren_cap50_mlf = (fin_tto$total_cap_milte_50_ftto / evaluacion_base$total_amp_mil_50_eb)*100
table(fin_tto$porcent_adheren_cap50_mlf)
fin_tto %>%
  filter(porcent_adheren_cap50_mlf <90) %>%
  dplyr::select(codigo_paciente, porcent_adheren_cap50_mlf, dias_tto_admido_ftto)

## Adherence for Miltefosine 10 mg capsules
fin_tto$porcent_adheren_cap10_mlf = (fin_tto$total_cap_milte_10_ftto / evaluacion_base$total_amp_cap_10_eb)*100
table(fin_tto$porcent_adheren_cap10_mlf)
fin_tto %>%
  filter(porcent_adheren_cap10_mlf <90) %>%
  dplyr::select(codigo_paciente, porcent_adheren_cap10_mlf, dias_tto_admido_ftto)

## Adherence summary data frame (example)
df_prueba2 <- data.frame(
  codigo = evaluacion_base$codigo_paciente,
  adherencia_dias = fin_tto$porcent_adheren_dias,
  adherencia_glc = fin_tto$porcent_adheren_ampoll_glc,
  adherencia_mlf_50 = fin_tto$porcent_adheren_cap50_mlf,
  adherencia_mlf_10 = fin_tto$porcent_adheren_cap10_mlf)

## Final treatment outcome
fin_tto$estado_fin_tto_ftto <- factor(fin_tto$estado_fin_tto_ftto,
                                      levels = c("1", "2", "4"),
                                      labels = c("Therapeutic failure",
                                                 "Improvement", 
                                                 "Apparent cure"))
table(fin_tto$estado_fin_tto_ftto)

fin_tto$fechaHoraCreacion <- as.Date(fin_tto$fechaHoraCreacion, format = "%YY-%MM-%DD")
fin_tto$fechaHoraCreacion[fin_tto$fechaHoraCreacion <= "2000-01-01"] <- NA

###
### Week 8 Database
### 

sem_8$fecha_evaluacion_s8 <- as.Date(sem_8$fecha_evaluacion_s8, format = "%YY-%MM-%DD")
sem_8$fecha_evaluacion_s8[sem_8$fecha_evaluacion_s8 <= "2000-01-01"] <- NA

sem_8$visita_eval_realizada_s8 <- factor(sem_8$visita_eval_realizada_s8,
                                         levels = c("0", "1"),
                                         labels= c("No", "Yes"))

sem_8$fecha_visita_s8 <- as.Date(sem_8$fecha_visita_s8, format = "%YY-%MM-%DD")
sem_8$fecha_visita_s8[sem_8$fecha_visita_s8 <= "2000-01-01"] <- NA
sem_8$dias_transcurridos_s8 <- as.numeric((difftime(sem_8$fecha_visita_s8, evaluacion_base$fecha_visita_eb,
                                                    units = "weeks"))*7)
summary(sem_8$dias_transcurridos_s8)

sem_8$estado_fin_tto_s8 <- factor(sem_8$estado_fin_tto_s8,
                                  levels = c("1", "2", "3","4"),
                                  labels= c("Therapeutic failure", "Improvement",
                                            "No change", "Apparent cure"))

###
### Week 13 Database
### 

sem_13$fecha_evaluacion_s13 <- as.Date(sem_13$fecha_evaluacion_s13, format = "%YY-%MM-%DD")
sem_13$fecha_evaluacion_s13[sem_13$fecha_evaluacion_s13 <= "2000-01-01"] <- NA

sem_13$visita_eval_realizada_s13 <- factor(sem_13$visita_eval_realizada_s13,
                                           levels = c("0", "1"),
                                           labels= c("No", "Yes"))

sem_13$fecha_visita_s13 <- as.Date(sem_13$fecha_visita_s13, format = "%YY-%MM-%DD")
sem_13$fecha_visita_s13[sem_13$fecha_visita_s13 <= "2000-01-01"] <- NA
sem_13$fecha_visita_s13[sem_13$fecha_visita_s13 <= "2000-01-01"] <- NA
sem_13$dias_transcurridos_s13 <- as.numeric((difftime(sem_13$fecha_visita_s13, evaluacion_base$fecha_visita_eb,
                                                      units = "weeks"))*7)
summary(sem_13$dias_transcurridos_s13)

sem_13 %>%
  filter(sem_13$dias_transcurridos_s13 >120) %>%
  dplyr::select(codigo_paciente)

sem_13$estado_fin_tto_s13 <- factor(sem_13$estado_fin_tto_s13,
                                    levels = c("0","1", "2", "3","4"),
                                    labels= c("Definitive cure", "Therapeutic failure", 
                                              "Improvement", "No change", "Apparent cure"))

sem_13$fechaHoraCreacion <- as.Date(sem_13$fechaHoraCreacion, format = "%YY-%MM-%DD")
sem_13$fechaHoraCreacion[sem_13$fechaHoraCreacion <= "2000-01-01"] <- NA

####
### Week 26 Database
####

sem_26$fecha_evaluacion_s26 <- as.Date(sem_26$fecha_evaluacion_s26, format = "%YY-%MM-%DD")
sem_26$fecha_evaluacion_s26[sem_26$fecha_evaluacion_s26 <= "2000-01-01"] <- NA

sem_26$visita_eval_realizada_s26 <- factor(sem_26$visita_eval_realizada_s26,
                                           levels = c("0", "1"),
                                           labels= c("No", "Yes"))

sem_26$fecha_visita_s26 <- as.Date(sem_26$fecha_visita_s26, format = "%YY-%MM-%DD")
sem_26$fecha_visita_s26[sem_26$fecha_visita_s26 <= "2000-01-01"] <- NA
sem_26$dias_transcurridos_s26 <- as.numeric((difftime(sem_26$fecha_visita_s26, evaluacion_base$fecha_visita_eb,
                                                      units = "weeks"))*7)
summary(sem_26$dias_transcurridos_s26)

sem_26 %>%
  filter(sem_26$dias_transcurridos_s26 >200) %>%
  dplyr::select(codigo_paciente)

sem_26$estado_fin_tto_s26 <- factor(sem_26$estado_fin_tto_s26,
                                    levels = c("0","1", "2", "4"),
                                    labels= c("Definitive cure", "Therapeutic failure",
                                              "Improvement", "Apparent cure"))

sem_26$fechaHoraCreacion <- as.Date(sem_26$fechaHoraCreacion, format = "%YY-%MM-%DD")
sem_26$fechaHoraCreacion[sem_26$fechaHoraCreacion <= "2000-01-01"] <- NA

####
### Additional Visit Database
####

visita_adic$fecha_evaluacion_va <- as.Date(visita_adic$fecha_evaluacion_va, format = "%YY-%MM-%DD")
visita_adic$fecha_evaluacion_va[visita_adic$fecha_evaluacion_va <= "2000-01-01"] <- NA

visita_adic$visita_eval_realizada_va <- factor(visita_adic$visita_eval_realizada_va,
                                               levels = c("0", "1"),
                                               labels= c("No", "Yes"))

visita_adic$fecha_visita_va <- as.Date(visita_adic$fecha_visita_va, format = "%YY-%MM-%DD")
visita_adic$fecha_visita_va[visita_adic$fecha_visita_va <= "2000-01-01"] <- NA
visita_adic$dias_transcurridos_va <- as.numeric((difftime(visita_adic$fecha_visita_va, evaluacion_base$fecha_visita_eb,
                                                          units = "weeks"))*7)
summary(visita_adic$dias_transcurridos_va)

visita_adic$estado_fin_tto_va <- factor(visita_adic$estado_fin_tto_va,
                                        levels = c("0","1", "2", "4"),
                                        labels= c("Definitive cure", "Therapeutic failure",
                                                  "Improvement", "Apparent cure"))

visita_adic$fechaHoraCreacion <- as.Date(visita_adic$fechaHoraCreacion, format = "%YY-%MM-%DD")
visita_adic$fechaHoraCreacion[visita_adic$fechaHoraCreacion <= "2000-01-01"] <- NA

####
### Parasitic Species Database
####

especie_parasit$fecha_evaluacion_especie <- as.Date(especie_parasit$fecha_evaluacion_especie, format = "%YY-%MM-%DD")
especie_parasit$fecha_evaluacion_especie[especie_parasit$fecha_evaluacion_especie <= "2000-01-01"] <- NA

especie_parasit$visita_eval_realizada_especie <- factor(especie_parasit$visita_eval_realizada_especie,
                                                        levels = c("0", "1"),
                                                        labels= c("No", "Yes"))

especie_parasit$fecha_visita_especie <- as.Date(especie_parasit$fecha_visita_especie, format = "%YY-%MM-%DD")
especie_parasit$fecha_visita_especie[especie_parasit$fecha_visita_especie <= "2000-01-01"] <- NA

especie_parasit$especie_paras_especie <- factor(especie_parasit$especie_paras_especie,
                                                levels = c("1", "2","3", "5"),
                                                labels= c("L. panamensis", "L. guyanensis","L. braziliensis", "L. viannia spp"))

especie_parasit$fechaHoraCreacion <- as.Date(especie_parasit$fechaHoraCreacion, format = "%YY-%MM-%DD")
especie_parasit$fechaHoraCreacion[especie_parasit$fechaHoraCreacion <= "2000-01-01"] <- NA

####
### Final State Database
####

estado_fin$fecha_evaluacion_ef <- as.Date(estado_fin$fecha_evaluacion_ef, format = "%YY-%MM-%DD")
estado_fin$fecha_evaluacion_ef[estado_fin$fecha_evaluacion_ef <= "2000-01-01"] <- NA

estado_fin$estado_fin_tto_ef <- factor(estado_fin$estado_fin_tto_ef,
                                       levels = c("0", "1"),
                                       labels = c("Definitive cure", "Therapeutic failure"))

estado_fin$fechaHoraCreacion <- as.Date(estado_fin$fechaHoraCreacion, format = "%YY-%MM-%DD")
estado_fin$fechaHoraCreacion[estado_fin$fechaHoraCreacion <= "2000-01-01"] <- NA

## SOCIODEMOGRAPHIC AND CLINICAL SUMMARY DATABASE

gran_base_resumen <- data.frame(codigo_paciente = participantes$codigo_paciente,
                                estado_final = estado_fin$estado_fin_tto_ef,
                                edad = evaluacion_base$edad_eb,
                                edad_categorica = evaluacion_base$edad_categorica,
                                sexo = evaluacion_base$sexo_nacimiento_eb,
                                etnia = evaluacion_base$grupo_etnico_eb,
                                antecedente_leish = evaluacion_base$historia_previa_eb,
                                tiempo_sintom_semanas = evaluacion_base$tiempo_sin_actual_eb,
                                peso = evaluacion_base$peso_eb,
                                talla = evaluacion_base$talla_eb,
                                imc = evaluacion_base$imc,
                                imc_categorico = evaluacion_base$imc_categorico,
                                numero_lesiones = evaluacion_base$num_lesiones_pre_eb,
                                lesiones_categorica = evaluacion_base$lesiones_categorica,
                                tipo_lesion_evalbas = evaluacion_base$tipo_lesion_eb,
                                adenopatia_evalbas = evaluacion_base$linfa_regional_eb,
                                infeccion_concom_evalbas = evaluacion_base$infeccion_concom_eb,
                                comorbilidades = evaluacion_base$comorbilidades_eb,
                                numero_comorbilidades = evaluacion_base$num_comorbilidades_eb,
                                comorb_cardio = evaluacion_base$comorb_cardio,
                                comorb_respira = evaluacion_base$comorb_respira,
                                comorb_gastroint = evaluacion_base$comorb_gastroint,
                                comorb_endocrin = evaluacion_base$comorb_endocrin,
                                comorb_neuro = evaluacion_base$comorb_neuro,
                                comorb_otra = evaluacion_base$comorb_otra,
                                hemo_pre_realizado = hemopre$hemo_tomado_pre_tto,
                                hemo_pos_realizado = hemopos$hemo_tomado_post_tto,
                                parasito_aislado = especie_parasit$visita_eval_realizada_especie,
                                especie = especie_parasit$especie_paras_especie,
                                tratamiento = evaluacion_base$tto_prescrito_eb,
                                dosis_glu_pres = evaluacion_base$dosis_glu_pres,
                                dosis_glu_anormal = evaluacion_base$dosis_glu_anormal,
                                dosis_mil_pres = evaluacion_base$dosis_mil_pres,
                                dosis_mil_anormal = evaluacion_base$dosis_mil_anormal,
                                rango_dosis_medicamento = evaluacion_base$rango_dosis_medicamento,
                                acude_fin_tto = fin_tto$visita_eval_realizada_ftto,
                                dias_fin_tto = fin_tto$dias_transcurridos_ftto,
                                adherencia_tto = fin_tto$porcent_adheren_dias,
                                variacion_lesion_post = fin_tto$cambio_lesion,
                                variacion_lesion_post2 = fin_tto$cambio_lesion2,
                                adenopatia_fin_tto = fin_tto$linfa_regional_ftto,
                                infeccion_concom_fintto = fin_tto$infeccion_concom_ftto,
                                adherencia_tto = fin_tto$porcent_adheren_dias,
                                estado_fin_tto = fin_tto$estado_fin_tto_ftto,
                                acude_sem8 = sem_8$visita_eval_realizada_s8,
                                dias_sem8 = sem_8$dias_transcurridos_s8,
                                estado_sem8 = sem_8$estado_fin_tto_s8,
                                acude_sem13 = sem_13$visita_eval_realizada_s13,
                                dias_sem13 = sem_13$dias_transcurridos_s13,
                                estado_sem13 = sem_13$estado_fin_tto_s13,
                                acude_sem26 = sem_26$visita_eval_realizada_s26,
                                dias_sem26 = sem_26$dias_transcurridos_s26,
                                estado_sem26 = sem_26$estado_fin_tto_s26,
                                acude_va = visita_adic$visita_eval_realizada_va,
                                dias_va = visita_adic$dias_transcurridos_va,
                                estado_va = visita_adic$estado_fin_tto_va,
                                estado_final = estado_fin$estado_fin_tto_ef)

gran_base_resumen <- gran_base_resumen %>% 
  mutate (tiempo_evolucion_dicotomica = case_when(
    tiempo_sintom_semanas > 4 ~ "0",
    tiempo_sintom_semanas <= 4 ~ "1")
  )

gran_base_resumen$tiempo_evolucion_dicotomica <- factor(gran_base_resumen$tiempo_evolucion_dicotomica,
                                                        levels = c("0", "1"),
                                                        labels = c("More than 4 weeks", "4 weeks or less"))

gran_base_resumen <- gran_base_resumen %>% 
  mutate (edad_categorica_corta = case_when(
    edad >= 17 & edad < 45 ~ "0",
    edad < 17 ~ "1",
    edad >= 45 ~ "2")
  )

gran_base_resumen$edad_categorica_corta <- factor(gran_base_resumen$edad_categorica_corta,
                                                  levels = c("0", "1", "2"),
                                                  labels = c("Between 17 and 44 years", "Between 1 and 16 years", "45 years or older"))

gran_base_resumen <- gran_base_resumen %>% 
  mutate (tipo_lesion_eval_base_corta = case_when(
    tipo_lesion_evalbas %in% c("Nodulo", "Papula", "Otra") ~ "1",
    tipo_lesion_evalbas == "Ulcera" ~ "0",
    tipo_lesion_evalbas == "Placa" ~ "1")
  )

gran_base_resumen$tipo_lesion_eval_base_corta <- factor(gran_base_resumen$tipo_lesion_eval_base_corta,
                                                        levels = c("0", "1"),
                                                        labels = c("Ulcer", "Non-ulcerated lesion"))

gran_base_resumen <- gran_base_resumen %>% 
  mutate (especie_corta = case_when(
    especie == "L. panamensis" ~ "0",
    especie == "L. guyanensis" ~ "0",
    especie == "L. viannia spp" ~ "0",
    especie == "L. braziliensis" ~ "1"
  ))

gran_base_resumen$especie_corta <- factor(gran_base_resumen$especie_corta,
                                          levels = c("0", "1"),
                                          labels = c("L. panamensis and other L. viannia spp", "L. braziliensis"))

############################
## HEMOGRAM SUMMARY DATABASE
#############################
### PHASE 1:
#### Cleaning, exploration and creation of new hemogram variables

## HEMOGRAMAS PRE

hemopre$fecha_evaluacion_pre_tto <- as.Date(hemopre$fecha_evaluacion_pre_tto, format = "%YY-%MM-%DD")
hemopre$fecha_evaluacion_pre_tto[hemopre$fecha_evaluacion_pre_tto <= "2000-01-01"] <- NA
hemopre$fecha_hemo_pretra_pre_tto <- as.Date(hemopre$fecha_hemo_pretra_pre_tto, format = "%YY-%MM-%DD")
hemopre$fecha_hemo_pretra_pre_tto[hemopre$fecha_hemo_pretra_pre_tto <= "2000-01-01"] <- NA
hemopre$dias_transcurridos_hemopre <- as.numeric((difftime(hemopre$fecha_hemo_pretra_pre_tto, evaluacion_base$fecha_visita_eb,
                                                           units = "weeks"))*7)
summary(hemopre$dias_transcurridos_hemopre)

hemopre %>%
  filter(dias_transcurridos_hemopre >10) %>%
  dplyr::select(codigo_paciente)

## The elapsed time (in days) between baseline evaluation and pre-treatment hemogram is correct;
## Some patients had delays of more than 20 days in starting treatment

## Exploratory analysis for each variable
EDA(hemopre$recuen_leuco_pre_tto)
EDA(hemopre$recuen_normo_pre_tto)
## (Variable with many missing values is considered non-informative and will not be included in analysis)
EDA(hemopre$recuen_neutro_pre_tto)
EDA(hemopre$recuen_linfo_pre_tto)
EDA(hemopre$recuen_mono_pre_tto)
EDA(hemopre$recuen_eosi_pre_tto)
EDA(hemopre$recuen_baso_pre_tto)
EDA(hemopre$recuen_granu_pre_tto)
hemopre %>% 
  filter(recuen_granu_pre_tto > 1) %>% 
  dplyr::select(codigo_paciente)
## Correct miscoding for patient PH2025: actual value is 0.02
hemopre$recuen_granu_pre_tto[hemopre$codigo_paciente == "PH2025"] <- 0.02

EDA(hemopre$recuen_granu_pre_tto)
hemopre %>% 
  filter(recuen_granu_pre_tto == 0) %>% 
  dplyr::select(codigo_paciente)
### Zeros are valid measurements (not NA) even if they may cause infinite values later

## Demonstration: the issue with zeros
i_neu_granu_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_granu_pre_tto
summary(i_neu_granu_pre)

## Using the exponential transform to avoid infinite values
i_neu_granu_pre = hemopre$recuen_neutro_pre_tto / exp(hemopre$recuen_granu_pre_tto)
summary(i_neu_granu_pre)

## Plot comparisons
plot(hemopre$recuen_neutro_pre_tto, hemopre$recuen_granu_pre_tto)
plot(hemopre$recuen_neutro_pre_tto, exp(hemopre$recuen_granu_pre_tto))

## Test subset for running models
pruebas <- data.frame( x = hemopre$recuen_granu_pre_tto, y = hemopre$recuen_neutro_pre_tto )
m1 <- lm(y ~ x, data = pruebas)
summary(m1) ## Model performance

library(ggplot2)

m1_g <- m1$model %>% 
  ggplot(aes(x = x, y = y))+
  geom_point()+
  geom_line(aes(x = x, y = m1$fitted.values), color = "Red")

## Test subset with exponential values
pruebas <- data.frame( x = exp(hemopre$recuen_granu_pre_tto), y = hemopre$recuen_neutro_pre_tto )
m2 <- lm(y ~ x, data = pruebas)
summary(m2) ## Model results are similar

m2_g <- m2$model %>% 
  ggplot(aes(x = x, y = y))+
  geom_point()+
  geom_line(aes(x = x, y = m2$fitted.values), color = "Red")

### The directionality of the models remains similar when using the exponential transform
gridExtra::grid.arrange(m1_g, m2_g, nrow = 1)

###
hemopre$recuen_granu_pre_tto_origi <- hemopre$recuen_granu_pre_tto
hemopre$recuen_granu_pre_tto <- exp(hemopre$recuen_granu_pre_tto)

####
EDA(hemopre$recuen_granu_pre_tto)

EDA(hemopre$recuen_glo_pre_tto)

EDA(hemopre$concen_hemo_pre_tto)

EDA(hemopre$porc_hemato_pre_tto)

EDA(hemopre$recu_plaque_pre_tto)

######
## HEMOGRAMAS POST
#####

hemopos$fecha_evaluacion_post_tto <- as.Date(hemopos$fecha_evaluacion_post_tto, format = "%YY-%MM-%DD")
hemopos$fecha_evaluacion_post_tto[hemopos$fecha_evaluacion_post_tto <= "2000-01-01"] <- NA
hemopos$fecha_hemo_pretra_post_tto <- as.Date(hemopos$fecha_hemo_pretra_post_tto, format = "%YY-%MM-%DD")
hemopos$fecha_hemo_pretra_post_tto[hemopos$fecha_hemo_pretra_post_tto <= "2000-01-01"] <- NA
hemopos$dias_transcurridos_hemopos <- as.numeric((difftime(hemopos$fecha_hemo_pretra_post_tto, evaluacion_base$fecha_visita_eb,
                                                           units = "weeks"))*7)
summary(hemopos$dias_transcurridos_hemopos)

hemopos %>%
  filter(dias_transcurridos_hemopos >40) %>%
  dplyr::select(codigo_paciente)

## Check if patients with more than 40 days difference are expected due to delay in treatment start

## Calculate time between hemograms
hemopos$tiempo_dias_entre_hemogramas <- as.numeric((difftime(hemopos$fecha_hemo_pretra_post_tto, hemopre$fecha_hemo_pretra_pre_tto,
                                                             units = "weeks"))*7)
summary(hemopos$tiempo_dias_entre_hemogramas)

## Exploratory analysis for post-hemogram variables
EDA(hemopos$recuen_leuco_post_tto)
#EDA(hemopos$recuen_normo_post_tto)
table(hemopos$recuen_normo_post_tto)
## Many missing values are considered non-informative and will not be included in analysis
EDA(hemopos$recuen_neutro_post_tto)
EDA(hemopos$recuen_linfo_post_tto)
EDA(hemopos$recuen_mono_post_tto)
hemopos %>% 
  filter(recuen_mono_post_tto > 2) %>% 
  dplyr::select(codigo_paciente, recuen_mono_post_tto)
## Correct miscoding for patient PH3001: actual value is 0.48
hemopos$recuen_mono_post_tto[hemopos$codigo_paciente == "PH3001"] <- 0.48
EDA(hemopos$recuen_mono_post_tto)
EDA(hemopos$recuen_eosi_post_tto)
hemopos %>% 
  filter(recuen_eosi_post_tto >= 1.2) %>% 
  dplyr::select(codigo_paciente, recuen_eosi_post_tto)
## Review of patients with high eosinophils (above 2.8); values are valid
EDA(hemopos$recuen_baso_post_tto)
hemopos %>% 
  filter(recuen_baso_post_tto >= 0.2) %>% 
  dplyr::select(codigo_paciente, recuen_baso_post_tto)
## Correct miscoding for patient PH2024: actual value is 0.02
hemopos$recuen_baso_post_tto[hemopos$codigo_paciente == "PH2024"] <- 0.02
EDA(hemopos$recuen_baso_post_tto)

EDA(hemopos$recuen_granu_post_tto)
hemopos %>% 
  filter(recuen_granu_post_tto == 0) %>% 
  dplyr::select(codigo_paciente)
### Zeros are maintained; to avoid infinite values in PCA, apply an exponential transform

i_neu_granu_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_granu_post_tto
summary(i_neu_granu_post)

## Use exponential transform to avoid zero issues
i_neu_granu_post = hemopos$recuen_neutro_post_tto / exp(hemopos$recuen_granu_post_tto)
summary(i_neu_granu_post)

## Plot comparisons
plot(hemopos$recuen_neutro_post_tto, hemopos$recuen_granu_post_tto)
plot(hemopos$recuen_neutro_post_tto, exp(hemopos$recuen_granu_post_tto))

## Create a test subset for models
pruebas <- data.frame( x = hemopos$recuen_granu_post_tto, y = hemopos$recuen_neutro_post_tto )
m1 <- lm(y ~ x, data = pruebas)
summary(m1)

m1_g <- m1$model %>% 
  ggplot(aes(x = x, y = y))+
  geom_point()+
  geom_line(aes(x = x, y = m1$fitted.values), color = "Red")

pruebas <- data.frame( x = exp(hemopos$recuen_granu_post_tto), y = hemopos$recuen_neutro_post_tto )
m2 <- lm(y ~ x, data = pruebas)
summary(m2)
m2_g <- m2$model %>% 
  ggplot(aes(x = x, y = y))+
  geom_point()+
  geom_line(aes(x = x, y = m2$fitted.values), color = "Red")

### Directionality remains similar with exponential transform
gridExtra::grid.arrange(m1_g, m2_g, nrow = 1)

### Save original and apply transform
hemopos$recuen_granu_post_tto_origi <- hemopos$recuen_granu_post_tto
hemopos$recuen_granu_post_tto <- exp(hemopos$recuen_granu_post_tto)

EDA(hemopos$recuen_granu_post_tto)
EDA(hemopos$recuen_glo_post_tto)
EDA(hemopos$concen_hemo_post_tto)
EDA(hemopos$porc_hemato_post_tto)

### Create master hemogram dataframe including new variables
Big_hemo <- data.frame(
  codigo_paciente = participantes$codigo_paciente,
  Leucocitos_pre = hemopre$recuen_leuco_pre_tto,
  Neutrofilos_pre = hemopre$recuen_neutro_pre_tto,
  Linfocitos_pre = hemopre$recuen_linfo_pre_tto,
  Monocitos_pre = hemopre$recuen_mono_pre_tto,
  Eosinofilos_pre = hemopre$recuen_eosi_pre_tto,
  Basofilos_pre = hemopre$recuen_baso_pre_tto,
  Granulocitos_pre = hemopre$recuen_granu_pre_tto_origi,
  Granulocitos_pre_exp = hemopre$recuen_granu_pre_tto,
  Globulos_rojos_pre = hemopre$recuen_glo_pre_tto,
  Hemoglobina_pre = hemopre$concen_hemo_pre_tto,
  Hematocrito_pre = hemopre$porc_hemato_pre_tto,
  Plaquetas_pre = hemopre$recu_plaque_pre_tto,
  Leucocitos_post = hemopos$recuen_leuco_post_tto,
  Neutrofilos_post = hemopos$recuen_neutro_post_tto,
  Linfocitos_post = hemopos$recuen_linfo_post_tto,
  Monocitos_post = hemopos$recuen_mono_post_tto,
  Eosinofilos_post = hemopos$recuen_eosi_post_tto,
  Basofilos_post = hemopos$recuen_baso_post_tto,
  Granulocitos_post = hemopos$recuen_granu_post_tto_origi,
  Granulocitos_post_exp = hemopos$recuen_granu_post_tto,
  Globulos_rojos_post = hemopos$recuen_glo_post_tto,
  Hemoglobina_post = hemopos$concen_hemo_post_tto,
  Hematocrito_post = hemopos$porc_hemato_post_tto,
  porcentaje_neutro_pre = 100*(hemopre$recuen_neutro_pre_tto / hemopre$recuen_leuco_pre_tto),
  porcentaje_linfo_pre = 100*(hemopre$recuen_linfo_pre_tto / hemopre$recuen_leuco_pre_tto),
  porcentaje_mono_pre = 100*(hemopre$recuen_mono_pre_tto / hemopre$recuen_leuco_pre_tto),
  porcentaje_eosino_pre = 100*(hemopre$recuen_eosi_pre_tto / hemopre$recuen_leuco_pre_tto),
  porcentaje_baso_pre = 100*(hemopre$recuen_baso_pre_tto / hemopre$recuen_leuco_pre_tto),
  porcentaje_granulo_pre = 100*(hemopos$recuen_granu_post_tto / hemopos$recuen_leuco_post_tto),
  porcentaje_neutro_post = 100*(hemopos$recuen_neutro_post_tto / hemopos$recuen_leuco_post_tto),
  porcentaje_linfo_post = 100*(hemopos$recuen_linfo_post_tto / hemopos$recuen_leuco_post_tto),
  porcentaje_mono_post = 100*(hemopos$recuen_mono_post_tto / hemopos$recuen_leuco_post_tto),
  porcentaje_eosino_post = 100*(hemopos$recuen_eosi_post_tto / hemopos$recuen_leuco_post_tto),
  porcentaje_baso_post = 100*(hemopos$recuen_baso_post_tto / hemopos$recuen_leuco_post_tto),
  porcentaje_granulo_post = 100*(hemopos$recuen_granu_post_tto / hemopos$recuen_leuco_post_tto),
  i_neu_linfo_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_linfo_pre_tto,
  i_eos_linfo_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_linfo_pre_tto,
  i_mono_linfo_pre = hemopre$recuen_mono_pre_tto / hemopre$recuen_linfo_pre_tto,
  i_baso_linfo_pre = hemopre$recuen_baso_pre_tto / hemopre$recuen_linfo_pre_tto,
  i_granu_linfo_pre = hemopre$recuen_granu_pre_tto / hemopre$recuen_linfo_pre_tto,
  i_neu_granu_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_granu_pre_tto,
  i_eos_granu_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_granu_pre_tto,
  i_baso_granu_pre = hemopre$recuen_baso_pre_tto / hemopre$recuen_granu_pre_tto,
  i_eos_mono_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_mono_pre_tto,
  i_eos_neu_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_neutro_pre_tto,
  i_eos_baso_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_baso_pre_tto,
  i_neu_mono_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_mono_pre_tto,
  i_neu_baso_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_baso_pre_tto,
  i_baso_mono_pre = hemopre$recuen_baso_pre_tto / hemopre$recuen_mono_pre_tto,
  i_monoeosneu_lin_pre = (hemopre$recuen_mono_pre_tto+hemopre$recuen_eosi_pre_tto+hemopre$recuen_neutro_pre_tto) / hemopre$recuen_linfo_pre_tto,
  i_neu_linfo_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_linfo_post_tto,
  i_eos_linfo_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_linfo_post_tto,
  i_mono_linfo_post = hemopos$recuen_mono_post_tto / hemopos$recuen_linfo_post_tto,
  i_baso_linfo_post = hemopos$recuen_baso_post_tto / hemopos$recuen_linfo_post_tto,
  i_granu_linfo_post = hemopos$recuen_granu_post_tto / hemopos$recuen_linfo_post_tto,
  i_neu_granu_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_granu_post_tto,
  i_eos_granu_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_granu_post_tto,
  i_baso_granu_post = hemopos$recuen_baso_post_tto / hemopos$recuen_granu_post_tto,
  i_eos_mono_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_mono_post_tto,
  i_eos_neu_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_neutro_post_tto,
  i_eos_baso_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_baso_post_tto,
  i_neu_mono_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_mono_post_tto,
  i_neu_baso_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_baso_post_tto,
  i_baso_mono_post = hemopos$recuen_baso_post_tto / hemopos$recuen_mono_post_tto,
  i_monoeosneu_lin_post = (hemopos$recuen_mono_post_tto+hemopos$recuen_eosi_post_tto+hemopos$recuen_neutro_post_tto) / hemopos$recuen_linfo_post_tto,
  variacion_leucocitos = hemopos$recuen_leuco_post_tto / hemopre$recuen_leuco_pre_tto,
  variacion_neutrofilos = hemopos$recuen_neutro_post_tto/hemopre$recuen_neutro_pre_tto,
  variacion_linfocitos = hemopos$recuen_linfo_post_tto / hemopre$recuen_linfo_pre_tto,
  variacion_monocitos = hemopos$recuen_mono_post_tto / hemopre$recuen_mono_pre_tto,
  variacion_eosinofilos = hemopos$recuen_eosi_post_tto / hemopre$recuen_eosi_pre_tto,
  variacion_basofilos = hemopos$recuen_baso_post_tto / hemopre$recuen_baso_pre_tto,
  variacion_granulocitos = hemopos$recuen_granu_post_tto / hemopre$recuen_granu_pre_tto,
  variacion_globulos_rojos = hemopos$recuen_glo_post_tto / hemopre$recuen_glo_pre_tto,
  variacion_hemoglobina = hemopos$concen_hemo_post_tto / hemopre$concen_hemo_pre_tto,
  variacion_hematocrito = hemopos$porc_hemato_post_tto / hemopre$porc_hemato_pre_tto,
  variacion_porcentaje_neutro = (100*(hemopos$recuen_neutro_post_tto / hemopos$recuen_leuco_post_tto)) / (100*(hemopre$recuen_neutro_pre_tto / hemopre$recuen_leuco_pre_tto)),
  variacion_porcentaje_linfo = (100*(hemopos$recuen_linfo_post_tto / hemopos$recuen_leuco_post_tto)) / (100*(hemopre$recuen_linfo_pre_tto / hemopre$recuen_leuco_pre_tto)),
  variacion_porcentaje_mono = (100*(hemopos$recuen_mono_post_tto / hemopos$recuen_leuco_post_tto)) / (100*(hemopre$recuen_mono_pre_tto / hemopre$recuen_leuco_pre_tto)),
  variacion_porcentaje_eosino = (100*(hemopos$recuen_eosi_post_tto / hemopos$recuen_leuco_post_tto)) / (100*(hemopre$recuen_eosi_pre_tto / hemopre$recuen_leuco_pre_tto)),
  variacion_porcentaje_baso = (100*(hemopos$recuen_baso_post_tto / hemopos$recuen_leuco_post_tto)) / (100*(hemopre$recuen_baso_pre_tto / hemopre$recuen_leuco_pre_tto)),
  variacion_porcentaje_granulo = (100*(hemopos$recuen_granu_post_tto / hemopos$recuen_leuco_post_tto)) / (100*(hemopre$recuen_granu_pre_tto / hemopre$recuen_leuco_pre_tto)),
  variacion_i_neu_linfo = (hemopos$recuen_neutro_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_linfo_pre_tto),
  variacion_i_eos_linfo = (hemopos$recuen_eosi_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_linfo_pre_tto),
  variacion_i_mono_linfo = (hemopos$recuen_mono_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_mono_pre_tto / hemopre$recuen_linfo_pre_tto),
  variacion_i_baso_linfo = (hemopos$recuen_baso_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_baso_pre_tto / hemopre$recuen_linfo_pre_tto),
  variacion_i_granu_linfo = (hemopos$recuen_granu_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_granu_pre_tto / hemopre$recuen_linfo_pre_tto),
  variacion_i_neu_granu = (hemopos$recuen_neutro_post_tto / hemopos$recuen_granu_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_granu_pre_tto),
  variacion_i_eos_granu = (hemopos$recuen_eosi_post_tto / hemopos$recuen_granu_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_granu_pre_tto),
  variacion_i_baso_granu = (hemopos$recuen_baso_post_tto / hemopos$recuen_granu_post_tto) / (hemopre$recuen_baso_pre_tto / hemopre$recuen_granu_pre_tto),
  variacion_i_eos_mono = (hemopos$recuen_eosi_post_tto / hemopos$recuen_mono_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_mono_pre_tto),
  variacion_i_eos_neu = (hemopos$recuen_eosi_post_tto / hemopos$recuen_neutro_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_neutro_pre_tto),
  variacion_i_eos_baso = (hemopos$recuen_eosi_post_tto / hemopos$recuen_baso_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_baso_pre_tto),
  variacion_i_neu_mono = (hemopos$recuen_neutro_post_tto / hemopos$recuen_mono_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_mono_pre_tto),
  variacion_i_neu_baso = (hemopos$recuen_neutro_post_tto / hemopos$recuen_baso_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_baso_pre_tto),
  variacion_i_baso_mono = (hemopos$recuen_baso_post_tto / hemopos$recuen_mono_post_tto) / (hemopre$recuen_baso_pre_tto / hemopre$recuen_mono_pre_tto),
  variacion_i_monoeosneu_lin = ((hemopos$recuen_mono_post_tto+hemopos$recuen_eosi_post_tto+hemopos$recuen_neutro_post_tto) / hemopos$recuen_linfo_post_tto) / ((hemopre$recuen_mono_pre_tto+hemopre$recuen_eosi_pre_tto+hemopre$recuen_neutro_pre_tto) / hemopre$recuen_linfo_pre_tto),
  Estado_final = estado_fin$estado_fin_tto_ef
)

### Verify that there are no infinite or extreme values in the new indices
EDA(Big_hemo$porcentaje_neutro_pre)
EDA(Big_hemo$porcentaje_linfo_pre)
EDA(Big_hemo$porcentaje_mono_pre)
EDA(Big_hemo$porcentaje_eosino_pre)
EDA(Big_hemo$porcentaje_baso_pre)
EDA(Big_hemo$porcentaje_granulo_pre)
EDA(Big_hemo$porcentaje_neutro_post)
EDA(Big_hemo$porcentaje_linfo_post)
EDA(Big_hemo$porcentaje_mono_post)
EDA(Big_hemo$porcentaje_eosino_post)
EDA(Big_hemo$porcentaje_baso_post)
EDA(Big_hemo$porcentaje_granulo_post)
EDA(Big_hemo$i_neu_linfo_pre)
EDA(Big_hemo$i_eos_linfo_pre)
EDA(Big_hemo$i_mono_linfo_pre)
EDA(Big_hemo$i_baso_linfo_pre)
EDA(Big_hemo$i_granu_linfo_pre)
EDA(Big_hemo$i_neu_granu_pre)
EDA(Big_hemo$i_eos_granu_pre)
EDA(Big_hemo$i_baso_granu_pre)
EDA(Big_hemo$i_eos_mono_pre)
EDA(Big_hemo$i_eos_neu_pre)
EDA(Big_hemo$i_eos_baso_pre)
EDA(Big_hemo$i_neu_mono_pre)
EDA(Big_hemo$i_neu_baso_pre)
EDA(Big_hemo$i_baso_mono_pre)
EDA(Big_hemo$i_monoeosneu_lin_pre)
EDA(Big_hemo$i_neu_linfo_post)
EDA(Big_hemo$i_eos_linfo_post)
EDA(Big_hemo$i_mono_linfo_post)
EDA(Big_hemo$i_baso_linfo_post)
EDA(Big_hemo$i_granu_linfo_post)
EDA(Big_hemo$i_neu_granu_post)
EDA(Big_hemo$i_eos_granu_post)
EDA(Big_hemo$i_baso_granu_post)
EDA(Big_hemo$i_eos_mono_post)
EDA(Big_hemo$i_eos_neu_post)
EDA(Big_hemo$i_eos_baso_post)
EDA(Big_hemo$i_neu_mono_post)
EDA(Big_hemo$i_neu_baso_post)
EDA(Big_hemo$i_baso_mono_post)
EDA(Big_hemo$i_monoeosneu_lin_post)
EDA(Big_hemo$variacion_leucocitos)
EDA(Big_hemo$variacion_neutrofilos)
EDA(Big_hemo$variacion_linfocitos)
EDA(Big_hemo$variacion_monocitos)
EDA(Big_hemo$variacion_eosinofilos)
EDA(Big_hemo$variacion_basofilos)
EDA(Big_hemo$variacion_globulos_rojos)
EDA(Big_hemo$variacion_basofilos)
EDA(Big_hemo$variacion_granulocitos)
EDA(Big_hemo$variacion_globulos_rojos)
EDA(Big_hemo$variacion_hemoglobina)
EDA(Big_hemo$variacion_hematocrito)
EDA(Big_hemo$variacion_porcentaje_neutro)
EDA(Big_hemo$variacion_porcentaje_linfo)
EDA(Big_hemo$variacion_porcentaje_mono)
EDA(Big_hemo$variacion_porcentaje_eosino)
EDA(Big_hemo$variacion_porcentaje_baso)
EDA(Big_hemo$variacion_porcentaje_granulo)
EDA(Big_hemo$variacion_i_neu_linfo)
EDA(Big_hemo$variacion_i_eos_linfo)
EDA(Big_hemo$variacion_i_mono_linfo)
EDA(Big_hemo$variacion_i_baso_linfo)
EDA(Big_hemo$variacion_i_granu_linfo)
EDA(Big_hemo$variacion_i_neu_granu)
EDA(Big_hemo$variacion_i_eos_granu)
EDA(Big_hemo$variacion_i_baso_granu)
EDA(Big_hemo$variacion_i_eos_mono)
EDA(Big_hemo$variacion_i_eos_neu)
EDA(Big_hemo$variacion_i_eos_baso)
EDA(Big_hemo$variacion_i_neu_mono)
EDA(Big_hemo$variacion_i_neu_baso)
EDA(Big_hemo$variacion_i_baso_mono)
EDA(Big_hemo$variacion_i_monoeosneu_lin)

## Before, creating the report failed because some indices tended to infinity
## The replacement of infinite values by NA is no longer needed

#create_report(Big_hemo)

## Ahora creo una base madre para analizarla en STATA en caso de que asi lo quiera

final_df_cleaned <- data.frame(codigo_paciente = participantes$codigo_paciente,
                               estado_final = estado_fin$estado_fin_tto_ef,
                               edad = evaluacion_base$edad_eb,
                               edad_categorica_corta = gran_base_resumen$edad_categorica_corta,
                               sexo = evaluacion_base$sexo_nacimiento_eb,
                               etnia = evaluacion_base$grupo_etnico_eb,
                               antecedente_leish = evaluacion_base$historia_previa_eb,
                               tiempo_sintom_semanas = evaluacion_base$tiempo_sin_actual_eb,
                               tiempo_evolucion_dicotomica = gran_base_resumen$tiempo_evolucion_dicotomica,
                               peso = evaluacion_base$peso_eb,
                               talla = evaluacion_base$talla_eb,
                               imc = evaluacion_base$imc,
                               imc_cat_corta = evaluacion_base$imc_cat_corta , 
                               numero_lesiones = evaluacion_base$num_lesiones_pre_eb,
                               lesiones_categorica = evaluacion_base$lesiones_categorica,
                               tipo_lesion_evalbas = evaluacion_base$tipo_lesion_eb,
                               tipo_lesion_eval_base_corta = gran_base_resumen$tipo_lesion_eval_base_corta,
                               adenopatia_evalbas = evaluacion_base$linfa_regional_eb,
                               infeccion_concom_evalbas = evaluacion_base$infeccion_concom_eb,
                               comorbilidades = evaluacion_base$comorbilidades_eb,
                               numero_comorbilidades = evaluacion_base$num_comorbilidades_eb,
                               comorb_cardio =evaluacion_base$comorb_cardio,
                               comorb_respira = evaluacion_base$comorb_respira,
                               comorb_gastroint = evaluacion_base$comorb_gastroint,
                               comorb_endocrin = evaluacion_base$comorb_endocrin,
                               comorb_neuro = evaluacion_base$comorb_neuro,
                               comorb_otra = evaluacion_base$comorb_otra,
                               hemo_pre_realizado = hemopre$hemo_tomado_pre_tto,
                               hemo_pos_realizado = hemopos$hemo_tomado_post_tto,
                               parasito_aislado = especie_parasit$visita_eval_realizada_especie,
                               especie = especie_parasit$especie_paras_especie,
                               especie_corta = gran_base_resumen$especie_corta,
                               tratamiento = evaluacion_base$tto_prescrito_eb,
                               dosis_glu_pres = evaluacion_base$dosis_glu_pres,
                               dosis_glu_anormal = evaluacion_base$dosis_glu_anormal,
                               dosis_mil_pres = evaluacion_base$dosis_mil_pres,
                               dosis_mil_anormal = evaluacion_base$dosis_mil_anormal,
                               rango_dosis_medicamento = evaluacion_base$rango_dosis_medicamento,
                               acude_fin_tto = fin_tto$visita_eval_realizada_ftto,
                               dias_fin_tto = fin_tto$dias_transcurridos_ftto,
                               adherencia_tto = fin_tto$porcent_adheren_dias,
                               variacion_lesion_post = fin_tto$cambio_lesion,
                               variacion_lesion_post2 = fin_tto$cambio_lesion2,
                               adenopatia_fin_tto = fin_tto$linfa_regional_ftto,
                               infeccion_concom_fintto = fin_tto$infeccion_concom_ftto,
                               estado_fin_tto = fin_tto$estado_fin_tto_ftto,
                               acude_sem8 = sem_8$visita_eval_realizada_s8,
                               dias_sem8 = sem_8$dias_transcurridos_s8,
                               estado_sem8 = sem_8$estado_fin_tto_s8,
                               acude_sem13 = sem_13$visita_eval_realizada_s13,
                               dias_sem13 = sem_13$dias_transcurridos_s13,
                               estado_sem13 = sem_13$estado_fin_tto_s13,
                               acude_sem26 = sem_26$visita_eval_realizada_s26,
                               dias_sem26 = sem_26$dias_transcurridos_s26,
                               estado_sem26 = sem_26$estado_fin_tto_s26,
                               acude_va = visita_adic$visita_eval_realizada_va,
                               dias_va = visita_adic$dias_transcurridos_va,
                               estado_va = visita_adic$estado_fin_tto_va,
                               Leucocitos_pre = hemopre$recuen_leuco_pre_tto,
                               Neutrofilos_pre = hemopre$recuen_neutro_pre_tto,
                               Linfocitos_pre = hemopre$recuen_linfo_pre_tto,
                               Monocitos_pre = hemopre$recuen_mono_pre_tto,
                               Eosinofilos_pre = hemopre$recuen_eosi_pre_tto,
                               Basofilos_pre = hemopre$recuen_baso_pre_tto,
                               Granulocitos_pre = hemopre$recuen_granu_pre_tto_origi,
                               Granulocitos_pre_exp = hemopre$recuen_granu_pre_tto,
                               Globulos_rojos_pre = hemopre$recuen_glo_pre_tto,
                               Hemoglobina_pre = hemopre$concen_hemo_pre_tto,
                               Hematocrito_pre = hemopre$porc_hemato_pre_tto,
                               Plaquetas_pre = hemopre$recu_plaque_pre_tto,
                               Leucocitos_post = hemopos$recuen_leuco_post_tto ,
                               Neutrofilos_post = hemopos$recuen_neutro_post_tto,
                               Linfocitos_post = hemopos$recuen_linfo_post_tto,
                               Monocitos_post = hemopos$recuen_mono_post_tto,
                               Eosinofilos_post = hemopos$recuen_eosi_post_tto,
                               Basofilos_post = hemopos$recuen_baso_post_tto,
                               Granulocitos_post = hemopos$recuen_granu_post_tto_origi,
                               Granulocitos_post_exp = hemopos$recuen_granu_post_tto,
                               Globulos_rojos_post = hemopos$recuen_glo_post_tto,
                               Hemoglobina_post = hemopos$concen_hemo_post_tto,
                               Hematocrito_post = hemopos$porc_hemato_post_tto,
                               porcentaje_neutro_pre = 100*(hemopre$recuen_neutro_pre_tto / hemopre$recuen_leuco_pre_tto),
                               porcentaje_linfo_pre = 100*(hemopre$recuen_linfo_pre_tto / hemopre$recuen_leuco_pre_tto),
                               porcentaje_mono_pre = 100*(hemopre$recuen_mono_pre_tto / hemopre$recuen_leuco_pre_tto),
                               porcentaje_eosino_pre = 100*(hemopre$recuen_eosi_pre_tto / hemopre$recuen_leuco_pre_tto),
                               porcentaje_baso_pre = 100*(hemopre$recuen_baso_pre_tto / hemopre$recuen_leuco_pre_tto),
                               porcentaje_granulo_pre = 100*(hemopos$recuen_granu_post_tto / hemopos$recuen_leuco_post_tto),
                               porcentaje_neutro_post = 100*(hemopos$recuen_neutro_post_tto / hemopos$recuen_leuco_post_tto),
                               porcentaje_linfo_post = 100*(hemopos$recuen_linfo_post_tto / hemopos$recuen_leuco_post_tto),
                               porcentaje_mono_post = 100*(hemopos$recuen_mono_post_tto / hemopos$recuen_leuco_post_tto),
                               porcentaje_eosino_post = 100*(hemopos$recuen_eosi_post_tto / hemopos$recuen_leuco_post_tto),
                               porcentaje_baso_post = 100*(hemopos$recuen_baso_post_tto / hemopos$recuen_leuco_post_tto),
                               porcentaje_granulo_post = 100*(hemopos$recuen_granu_post_tto / hemopos$recuen_leuco_post_tto),
                               i_neu_linfo_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_linfo_pre_tto,
                               i_eos_linfo_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_linfo_pre_tto,
                               i_mono_linfo_pre = hemopre$recuen_mono_pre_tto / hemopre$recuen_linfo_pre_tto,
                               i_baso_linfo_pre = hemopre$recuen_baso_pre_tto / hemopre$recuen_linfo_pre_tto,
                               i_granu_linfo_pre = hemopre$recuen_granu_pre_tto / hemopre$recuen_linfo_pre_tto,
                               i_neu_granu_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_granu_pre_tto,
                               i_eos_granu_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_granu_pre_tto,
                               i_baso_granu_pre = hemopre$recuen_baso_pre_tto / hemopre$recuen_granu_pre_tto,
                               i_eos_mono_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_mono_pre_tto,
                               i_eos_neu_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_neutro_pre_tto,
                               i_eos_baso_pre = hemopre$recuen_eosi_pre_tto / hemopre$recuen_baso_pre_tto,
                               i_neu_mono_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_mono_pre_tto,
                               i_neu_baso_pre = hemopre$recuen_neutro_pre_tto / hemopre$recuen_baso_pre_tto,
                               i_baso_mono_pre = hemopre$recuen_baso_pre_tto / hemopre$recuen_mono_pre_tto,
                               i_monoeosneu_lin_pre = (hemopre$recuen_mono_pre_tto+hemopre$recuen_eosi_pre_tto+hemopre$recuen_neutro_pre_tto) / hemopre$recuen_linfo_pre_tto,
                               i_neu_linfo_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_linfo_post_tto,
                               i_eos_linfo_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_linfo_post_tto,
                               i_mono_linfo_post = hemopos$recuen_mono_post_tto / hemopos$recuen_linfo_post_tto,
                               i_baso_linfo_post = hemopos$recuen_baso_post_tto / hemopos$recuen_linfo_post_tto,
                               i_granu_linfo_post = hemopos$recuen_granu_post_tto / hemopos$recuen_linfo_post_tto,
                               i_neu_granu_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_granu_post_tto,
                               i_eos_granu_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_granu_post_tto,
                               i_baso_granu_post = hemopos$recuen_baso_post_tto / hemopos$recuen_granu_post_tto,
                               i_eos_mono_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_mono_post_tto,
                               i_eos_neu_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_neutro_post_tto,
                               i_eos_baso_post = hemopos$recuen_eosi_post_tto / hemopos$recuen_baso_post_tto,
                               i_neu_mono_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_mono_post_tto,
                               i_neu_baso_post = hemopos$recuen_neutro_post_tto / hemopos$recuen_baso_post_tto,
                               i_baso_mono_post = hemopos$recuen_baso_post_tto / hemopos$recuen_mono_post_tto,
                               i_monoeosneu_lin_post = (hemopos$recuen_mono_post_tto+hemopos$recuen_eosi_post_tto+hemopos$recuen_neutro_post_tto) / hemopos$recuen_linfo_post_tto,
                               variacion_leucocitos = hemopos$recuen_leuco_post_tto / hemopre$recuen_leuco_pre_tto,
                               variacion_neutrofilos = hemopos$recuen_neutro_post_tto/hemopre$recuen_neutro_pre_tto,
                               variacion_linfocitos = hemopos$recuen_linfo_post_tto / hemopre$recuen_linfo_pre_tto,
                               variacion_monocitos = hemopos$recuen_mono_post_tto / hemopre$recuen_mono_pre_tto,
                               variacion_eosinofilos = hemopos$recuen_eosi_post_tto / hemopre$recuen_eosi_pre_tto,
                               variacion_basofilos = hemopos$recuen_baso_post_tto / hemopre$recuen_baso_pre_tto,
                               variacion_granulocitos = hemopos$recuen_granu_post_tto / hemopre$recuen_granu_pre_tto,
                               variacion_globulos_rojos = hemopos$recuen_glo_post_tto / hemopre$recuen_glo_pre_tto,
                               variacion_hemoglobina = hemopos$concen_hemo_post_tto / hemopre$concen_hemo_pre_tto,
                               variacion_hematocrito = hemopos$porc_hemato_post_tto / hemopre$porc_hemato_pre_tto,
                               variacion_porcentaje_neutro = (100*(hemopos$recuen_neutro_post_tto / hemopos$recuen_leuco_post_tto)) / (100 *(hemopre$recuen_neutro_pre_tto / hemopre$recuen_leuco_pre_tto)),
                               variacion_porcentaje_linfo = (100*(hemopos$recuen_linfo_post_tto / hemopos$recuen_leuco_post_tto)) / (100 *(hemopre$recuen_linfo_pre_tto / hemopre$recuen_leuco_pre_tto)),
                               variacion_porcentaje_mono = (100*(hemopos$recuen_mono_post_tto / hemopos$recuen_leuco_post_tto)) / (100 *(hemopre$recuen_mono_pre_tto / hemopre$recuen_leuco_pre_tto)),
                               variacion_porcentaje_eosino = (100*(hemopos$recuen_eosi_post_tto / hemopos$recuen_leuco_post_tto)) / (100 *(hemopre$recuen_eosi_pre_tto / hemopre$recuen_leuco_pre_tto)),
                               variacion_porcentaje_baso = (100*(hemopos$recuen_baso_post_tto / hemopos$recuen_leuco_post_tto)) / (100 *(hemopre$recuen_baso_pre_tto / hemopre$recuen_leuco_pre_tto)),
                               variacion_porcentaje_granulo = (100*(hemopos$recuen_granu_post_tto / hemopos$recuen_leuco_post_tto)) / (100 *(hemopre$recuen_granu_pre_tto / hemopre$recuen_leuco_pre_tto)),
                               variacion_i_neu_linfo = (hemopos$recuen_neutro_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_linfo_pre_tto),
                               variacion_i_eos_linfo = (hemopos$recuen_eosi_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_linfo_pre_tto),
                               variacion_i_mono_linfo = (hemopos$recuen_mono_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_mono_pre_tto / hemopre$recuen_linfo_pre_tto),
                               variacion_i_baso_linfo = (hemopos$recuen_baso_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_baso_pre_tto / hemopre$recuen_linfo_pre_tto),
                               variacion_i_granu_linfo = (hemopos$recuen_granu_post_tto / hemopos$recuen_linfo_post_tto) / (hemopre$recuen_granu_pre_tto / hemopre$recuen_linfo_pre_tto),
                               variacion_i_neu_granu = (hemopos$recuen_neutro_post_tto / hemopos$recuen_granu_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_granu_pre_tto),
                               variacion_i_eos_granu = (hemopos$recuen_eosi_post_tto / hemopos$recuen_granu_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_granu_pre_tto),
                               variacion_i_baso_granu = (hemopos$recuen_baso_post_tto / hemopos$recuen_granu_post_tto) / (hemopre$recuen_baso_pre_tto / hemopre$recuen_granu_pre_tto),
                               variacion_i_eos_mono = (hemopos$recuen_eosi_post_tto / hemopos$recuen_mono_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_mono_pre_tto),
                               variacion_i_eos_neu = (hemopos$recuen_eosi_post_tto / hemopos$recuen_neutro_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_neutro_pre_tto),
                               variacion_i_eos_baso = (hemopos$recuen_eosi_post_tto / hemopos$recuen_baso_post_tto) / (hemopre$recuen_eosi_pre_tto / hemopre$recuen_baso_pre_tto),
                               variacion_i_neu_mono = (hemopos$recuen_neutro_post_tto / hemopos$recuen_mono_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_mono_pre_tto),
                               variacion_i_neu_baso = (hemopos$recuen_neutro_post_tto / hemopos$recuen_baso_post_tto) / (hemopre$recuen_neutro_pre_tto / hemopre$recuen_baso_pre_tto),
                               variacion_i_baso_mono = (hemopos$recuen_baso_post_tto / hemopos$recuen_mono_post_tto) / (hemopre$recuen_baso_pre_tto / hemopre$recuen_mono_pre_tto),
                               variacion_i_monoeosneu_lin = ((hemopos$recuen_mono_post_tto+hemopos$recuen_eosi_post_tto+hemopos$recuen_neutro_post_tto) / hemopos$recuen_linfo_post_tto) / ((hemopre$recuen_mono_pre_tto+hemopre$recuen_eosi_pre_tto+hemopre$recuen_neutro_pre_tto) / hemopre$recuen_linfo_pre_tto)
                               )


## REPORT AFTER DATA CLEANING

# Generate the exploratory analysis report
create_report(final_df_cleaned, 
              y = "estado_final", 
              report_title = "Final Clean Data Exploratory Report",
              output_file = "Reporte_Limpieza_Final.html",
              output_dir = "Reports")

# Center the data frame for easier odds interpretation in STATA and R
base_regre_centrada <- Big_hemo
base_regre_centrada <- subset(base_regre_centrada, select = -c(codigo_paciente, Estado_final))

center_scale <- function(x) {
  scale(x, scale = FALSE)
}

base_regre_centrada <- center_scale(base_regre_centrada)
base_regre_centrada <- as.data.frame(base_regre_centrada)
base_regre_centrada$codigo_paciente <- Big_hemo$codigo_paciente
base_regre_centrada$Estado_final <- gran_base_resumen$estado_final.1

## Save the final cleaned datasets
save(participantes, file = "data/Clean_data_RData/participantes.RData")
save(criterios_inclusion, file ="data/Clean_data_RData/criterios_inclusion.RData")
save(evaluacion_base, file ="data/Clean_data_RData/evaluacion_base.RData")
save(hemopre, file ="data/Clean_data_RData/hemopre.RData")
save(fin_tto, file ="data/Clean_data_RData/fin_tto.RData")
save(hemopos, file ="data/Clean_data_RData/hemopos.RData")
save(sem_8, file ="data/Clean_data_RData/sem_8.RData")
save(sem_13, file ="data/Clean_data_RData/sem_13.RData")
save(sem_26, file ="data/Clean_data_RData/sem_26.RData")
save(visita_adic, file ="data/Clean_data_RData/visita_adic.RData")
save(especie_parasit, file ="data/Clean_data_RData/especie_parasit.RData")
save(estado_fin, file ="data/Clean_data_RData/estado_fin.RData")
save(gran_base_resumen, file ="data/Clean_data_RData/gran_base_resumen.RData")
save(Big_hemo, file ="data/Clean_data_RData/Big_hemo.RData")
save(base_regre_centrada, file = "data/Clean_data_RData/hemogramas_centrados.Rdta")
save(final_df_cleaned, file ="data/Clean_data_RData/final_df_cleaned.RData")

## Save the datasets as CSV
write.csv(participantes, file = "data/Clean_data_csv/participantes.csv")
write.csv(criterios_inclusion, file ="data/Clean_data_csv/criterios_inclusion.csv")
write.csv(evaluacion_base, file ="data/Clean_data_csv/evaluacion_base.csv")
write.csv(hemopre, file ="data/Clean_data_csv/hemopre.csv")
write.csv(fin_tto, file ="data/Clean_data_csv/fin_tto.csv")
write.csv(hemopos, file ="data/Clean_data_csv/hemopos.csv")
write.csv(sem_8, file ="data/Clean_data_csv/sem_8.csv")
write.csv(sem_13, file ="data/Clean_data_csv/sem_13.csv")
write.csv(sem_26, file ="data/Clean_data_csv/sem_26.csv")
write.csv(visita_adic, file ="data/Clean_data_csv/visita_adic.csv")
write.csv(especie_parasit, file ="data/Clean_data_csv/especie_parasit.csv")
write.csv(estado_fin, file ="data/Clean_data_csv/estado_fin.csv")
write.csv(gran_base_resumen, file ="data/Clean_data_csv/gran_base_resumen.csv")
write.csv(Big_hemo, file ="data/Clean_data_csv/Big_hemo.csv")
write.csv(base_regre_centrada, file = "data/Clean_data_csv/hemogramas_centrados.csv")
write.csv(final_df_cleaned, file ="data/Clean_data_csv/final_df_cleaned.csv")

## Save the cleaned datasets in STATA (.dta) format
write.dta(participantes, file = "data/Clean_data_STATA_dta/participantes.dta")
write.dta(criterios_inclusion, file ="data/Clean_data_STATA_dta/criterios_inclusion.dta")
write.dta(evaluacion_base, file ="data/Clean_data_STATA_dta/evaluacion_base.dta")
write.dta(hemopre, file ="data/Clean_data_STATA_dta/hemopre.dta")
write.dta(fin_tto, file ="data/Clean_data_STATA_dta/fin_tto.dta")
write.dta(hemopos, file ="data/Clean_data_STATA_dta/hemopos.dta")
write.dta(sem_8, file ="data/Clean_data_STATA_dta/sem_8.dta")
write.dta(sem_13, file ="data/Clean_data_STATA_dta/sem_13.dta")
write.dta(sem_26, file ="data/Clean_data_STATA_dta/sem_26.dta")
write.dta(visita_adic, file ="data/Clean_data_STATA_dta/visita_adic.dta")
write.dta(especie_parasit, file ="data/Clean_data_STATA_dta/especie_parasit.dta")
write.dta(estado_fin, file ="data/Clean_data_STATA_dta/estado_fin.dta")
write.dta(gran_base_resumen, file ="data/Clean_data_STATA_dta/gran_base_resumen.dta")
write.dta(Big_hemo, file ="data/Clean_data_STATA_dta/Big_hemo.dta")
write.dta(base_regre_centrada, file = "data/Clean_data_STATA_dta/hemogramas_centrados.dta")
write.dta(final_df_cleaned, file ="data/Clean_data_STATA_dta/final_df_cleaned.dta")
